<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
  *
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2009 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="footer-container">
    <div class="page">
        <div class="footer">
            <div class="full-width">
				<div class="container">
                    <?php echo $this->getChildHtml('store_language') ?>					                
					<?php echo $this->getChildHtml('cms_footer_links') ?>
                    <?php echo $this->getChildHtml('footer_links') ?>    
                </div>
                <?php echo $this->getChildHtml('currency') ?> 
                <p class="copy"><?php echo $this->getCopyright() ?></p>
                <br class="clear" />
                <?php echo $this->getChildHtml('store_switcher') ?>
                <!--{%FOOTER_LINK}-->
                <br class="clear" />
           </div>
        </div>
    </div>
</div>