
<?php
$template = 'raovat_';
define("admin",$template."admin",true);
define("intro",$template."intro",true);
define("menu_product",$template."menu_product",true);
define("ads",$template."ads",true);
define("contact",$template."contact",true);
define("slide",$template."slide",true);
define("config",$template."config",true);
define("query",$template."query",true);
define("confirm",$template."confirm",true);
define("check",$template."check",true);
define("tinh",$template."tinh",true);
define("adv",$template."adv",true);
define("team",$template."team",true);
define("team_member",$template."team_member",true);
define("members",$template."members",true);
define("guide",$template."guide",true);
define("userpost",$template."userpost",true);
define("menu_service",$template."menu_service",true);
define("manacategory",$template."manacategory",true);
define("feedback",$template."feedback",true);
define("msg",$template."msg",true);
define("msg1",$template."msg1",true);
define("support",$template."support",true);
define("statis",$template."statis",true);
define("online",$template."online",true);
?>